### ISSUE TITLE
錯誤！找不到玉米濃湯(小)  這品項

### ISSUE THREAD

**Issue by Boteium** [agudoe2/CPKing_KFC#1]
玉米濃湯(小)  會讀不到

暫時解法：
"名稱,優惠代碼,連結" 那行最後補一個 "," 字元

**Comment by agudoe2** [comment]
google sheet export出來的csv有帶crlf，perl chomp 沒辦法處理，改用以下方法解法。Thanks~ :)
http://www.perlmonks.org/?node_id=549385
